services:
  bsp_postgres:
    image: postgres:16-alpine # Standard, lightweight stable enterprise engine
    container_name: bsp_local_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bsp1234
      POSTGRES_DB: bsplocal_digital_platform
    ports:
      - "5433:5432" # Maps standard database port to their localhost
    volumes:
      - bsp_db_data:/var/lib/postgresql/data # Saves data so it persists when laptop reboots

volumes:
  bsp_db_data: