services:
  bsp_postgres:
    image: postgres:16-alpine
    container_name: bsp_local_db_container

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bsp1234
      POSTGRES_DB: bsplocal_digital_platform

    ports:
      - "5433:5432"

    volumes:
      - bsp_db_data:/var/lib/postgresql/data


volumes:
  bsp_db_data: